### ISSUE TITLE
The GAP Project needs an account on Docker hub

### ISSUE THREAD

**Issue by snim2** [gap-system/gap-container#1]
Sign up page is here: https://hub.docker.com/account/signup/

**Comment by DevasenaInupakutika** [comment]
Just the GAP project needs account or people contributing to the repo also need account?

**Comment by snim2** [comment]
Good question. In the longer term GAP would be using the account, so it makes sense for GAP to have one, and to be building this repo there automatically.

I'm not sure whether it is better for us to have individual accounts and try to all build the repo, or have individual accounts and build our own forks of the repo, or for Alexander to give us the log in details to the GAP account.

What do you think?

**Comment by snim2** [comment]
Account can be found here: https://hub.docker.com/u/gapsystem/
