### ISSUE TITLE
Upgrade C compiler

### ISSUE THREAD

**Issue by olexandr-konovalov** [gap-system/gap-container#10]
groupoids package by @cdwensley currently crashes in the  master branch if Semigroups package is loaded: see for example https://travis-ci.org/gap-system/gap-docker-pkg-tests-master/jobs/333933165 :
```
terminate called after throwing an instance of 'std::system_error'
  what():  Enable multithreading to use std::thread: Operation not permitted
```
Indeed, the version of gcc there is 4.8.4 and @james-d-mitchell confirms that it is not compatible with Semigroups (although I haven't been able to find in Semigroups documentation what is the minimal compatible version then). 

It will be useful to upgrade the compiler to some modern version - that will not only help to groupoids tests, but to other tests involving Semigroups, and to users who would like to use Semigroups in the Docker container.

**Comment by james-d-mitchell** [comment]
There’s a bug in gcc 4.8 relating to multithreading, everything should be ok with gcc 5 or later.

**Comment by sebasguts** [comment]
Well, this is not that easy. We could either update to ubuntu xenial, giving us a standard gcc-4.9. Or wait for beaver, which should have a gcc-6 as standard (as far as I can see). Would you be happy with 4.9?

**Comment by james-d-mitchell** [comment]
I'm not completely sure if GCC 4.9 is ok or not, there is some discussion of the GCC issue here:

https://stackoverflow.com/questions/19463602/compiling-multithread-code-with-g

Following the links in that post, I can't see in which version of GCC the bug is fixed.

**Comment by james-d-mitchell** [comment]
I just checked and the same issue shows up with GCC 4.9.4, see:

https://travis-ci.org/james-d-mitchell/libsemigroups/jobs/341808034

So, it looks like GCC 5.0 or higher is really required to make this work. I am going to add an error to the next version of Semigroups (3.0.14) so that it refuses to compile if a too old version of GCC is used.

**Comment by olexandr-konovalov** [comment]
[BionicBeaver is due April 26](https://wiki.ubuntu.com/BionicBeaver/ReleaseSchedule) - that's after the anticipated date of GAP 4.9 public releases. Is there any easier way to get more modern gcc? Otherwise are keeping Semigroups in the [staging build](https://travis-ci.org/gap-system/gap-docker-pkg-tests-stable-4.9-staging) while in fact it seems to have no problems, and @james-d-mitchell has all reasons not to be very happy about this...

**Comment by sebasguts** [comment]
Did some more research, and apparently there is a [gcc-5 package for xenial](https://packages.ubuntu.com/xenial/gcc-5): Will try how far I can get with this one.

**Comment by james-d-mitchell** [comment]
We are using gcc-5 in travis in xenial (I think), if that is in anyway helpful.

**Comment by olexandr-konovalov** [comment]
If #11 will go well, we will have gcc-5 working. It is now merged, we will have to see how it will work.

**Comment by olexandr-konovalov** [comment]
Done in ff480bc47f96c42a6419ae615182538a374091ab - upgrated to bionic, now gives gcc-7 by default.
