### ISSUE TITLE
Add documentation for basic use of the Docker container

### ISSUE THREAD

**Issue by snim2** [gap-system/gap-container#2]
This page:

https://github.com/futurecore/parallella-devenv/blob/master/screenshots/HOWTO.md

describes how to create an animated gif of the command line. This would be useful documentation for the README of this repository.

**Comment by snim2** [comment]
Account can be found here: https://hub.docker.com/u/gapsystem/

**Comment by olexandr-konovalov** [comment]
Further instructions are now at https://hub.docker.com/r/gapsystem/gap-docker/
