### ISSUE TITLE
Split the docker container into several separate containers

### ISSUE THREAD

**Issue by snim2** [gap-system/gap-container#3]
The current container includes GAP and several packages. It would be more convenient to have a basie image which includes GAP and then derive other containers for each package.

The `FROM` keyword is useful here: https://docs.docker.com/reference/builder/#from

It may also be worth considering whether and how to use tags: https://docs.docker.com/userguide/dockerimages/#setting-tags-on-an-image

**Comment by olexandr-konovalov** [comment]
Yes, I agree that this is a good idea. For example, in the case of an update release (when the same GAP core system is released with newer packages) there will no need to recompile the GAP kernel. 

We do have already have separate archives of the GAP core system and of GAP packages, so it would be easy to switch the Docker container to use them. We do not advise the users to install GAP using them, however. These archives are intended for use by the providers of alternative GAP distributions - and Docker container would be one of them. 

My question would be if we want this basic image to be usable on its own. Perhaps yes, at least to be able to test it. Then it will require at least one package to add: this is GAPDoc which is needed by GAP. I am going to create and use `packages-required-stable-v4.7.7.tar.gz` archive which at the moment will contain only GAPDoc (but there may be more packages like this in the future).

Remark for myself: such archive was independently requested by @ChrisJefferson, together with `packages-required-master.tar.gz` and `packages-required-stable-4.7.tar.gz`

**Comment by snim2** [comment]
This sounds very sensible. Given that you have two different communities of users (package maintainers and end users) maybe it is worth thinking about how to create different sorts of Docker containers for different purposes, and how to point people to the one that is most useful for them?

**Comment by olexandr-konovalov** [comment]
Done - we have now Docker images called `gap-container` and `gap-docker`. The first has only GAPDoc packages to be runnable, the latter is developing into the direction of providing as much packages as possible.

This issue is closed and now superseded by #4, discussing whether we need more images in our pipeline.
