### ISSUE TITLE
Avoid && on Dockerfile?

### ISSUE THREAD

**Issue by rgaiacs** [gap-system/gap-container#7]
The `Dockerfile` has

~~~
RUN sudo apt-get update -qq \
    && sudo apt-get -qq install -y build-essential m4 libreadline6-dev libncurses5-dev wget unzip libgmp3-dev cmake \
    && adduser --quiet --shell /bin/bash --gecos "GAP user,101,," --disabled-password gap \
...
~~~

I believe that replace it with 

~~~
RUN sudo apt-get update -qq
RUN sudo apt-get -qq install -y build-essential m4 libreadline6-dev libncurses5-dev wget unzip libgmp3-dev cmake
RUN adduser --quiet --shell /bin/bash --gecos "GAP user,101,," --disabled-password gap \
...
~~~

is the Docker way because

1. Docker will stop the building if any line fail to execute properly, i.e. the return code is 0, and
2. Docker create a "layer" for each line and the first line that you change is used as start point for new rebuilds.

**Comment by sebasguts** [comment]
Actually, probably a shell script would be the best way. 

Multiple layers are not always wanted. for example, the lines
```
&& wget http://www.gap-system.org/Manuals/doc/gap4r8p6_manuals.tar.gz \
&& tar xvzf gap4r8p6_manuals.tar.gz \
&& rm gap4r8p6_manuals.tar.gz \
```
have to stay this way to not blow up the size of the image. But I think some reorganization can be useful.

**Comment by snim2** [comment]
As @sebasguts mentioned, the reason for having `&&` everywhere was to avoid having a layer per line and keep the size of the image reasonably small. It is a pain if you end up with a bug in the middle of a very long line, so an external script might well be helpful for testing.
